providers = ["node", "php"]


[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Skipping build, using pre-built dist'"]

[start]
# We let the default PHP provider handle the start command (Nginx + PHP-FPM)
