providers = ["node", "php"]


[phases.install]
cmds = ["npm install", "cd frontend && npm install --include=dev"]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "php backend/scripts/migrate.php && php-fpm -y /etc/php-fpm.conf && nginx -c /etc/nginx/nginx.conf"
