providers = ["node", "php"]


[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Skipping build, using pre-built dist'"]

[start]
cmd = "php backend/scripts/migrate.php && php-fpm -y /etc/php-fpm.conf && nginx -c /etc/nginx/nginx.conf"
